/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppInboxRouteImport } from './routes/app.inbox'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as ApiMetricsRouteImport } from './routes/api.metrics'
import { Route as AppProjectsIndexRouteImport } from './routes/app.projects.index'
import { Route as AppProjectsNewRouteImport } from './routes/app.projects.new'
import { Route as AppProjectsIdRouteImport } from './routes/app.projects.$id'
import { Route as AppAnalysisIdRouteImport } from './routes/app.analysis.$id'
import { Route as AppAdminUsersRouteImport } from './routes/app.admin.users'
import { Route as AppAdminMetricsRouteImport } from './routes/app.admin.metrics'
import { Route as AppAdminFeatureFlagsRouteImport } from './routes/app.admin.feature-flags'
import { Route as AppAdminExportRouteImport } from './routes/app.admin.export'
import { Route as AppAdminAuditLogsRouteImport } from './routes/app.admin.audit-logs'
import { Route as AppAdminApiMetricsRouteImport } from './routes/app.admin.api-metrics'
import { Route as AppAdminAiUsageRouteImport } from './routes/app.admin.ai-usage'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const ApiMetricsRoute = ApiMetricsRouteImport.update({
  id: '/api/metrics',
  path: '/api/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsNewRoute = AppProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIdRoute = AppProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalysisIdRoute = AppAnalysisIdRouteImport.update({
  id: '/analysis/$id',
  path: '/analysis/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminMetricsRoute = AppAdminMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminFeatureFlagsRoute = AppAdminFeatureFlagsRouteImport.update({
  id: '/feature-flags',
  path: '/feature-flags',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminExportRoute = AppAdminExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAuditLogsRoute = AppAdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminApiMetricsRoute = AppAdminApiMetricsRouteImport.update({
  id: '/api-metrics',
  path: '/api-metrics',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAiUsageRoute = AppAdminAiUsageRouteImport.update({
  id: '/ai-usage',
  path: '/ai-usage',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/metrics': typeof ApiMetricsRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/history': typeof AppHistoryRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/ai-usage': typeof AppAdminAiUsageRoute
  '/app/admin/api-metrics': typeof AppAdminApiMetricsRoute
  '/app/admin/audit-logs': typeof AppAdminAuditLogsRoute
  '/app/admin/export': typeof AppAdminExportRoute
  '/app/admin/feature-flags': typeof AppAdminFeatureFlagsRoute
  '/app/admin/metrics': typeof AppAdminMetricsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/analysis/$id': typeof AppAnalysisIdRoute
  '/app/projects/$id': typeof AppProjectsIdRoute
  '/app/projects/new': typeof AppProjectsNewRoute
  '/app/projects/': typeof AppProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/metrics': typeof ApiMetricsRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/history': typeof AppHistoryRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app': typeof AppIndexRoute
  '/app/admin/ai-usage': typeof AppAdminAiUsageRoute
  '/app/admin/api-metrics': typeof AppAdminApiMetricsRoute
  '/app/admin/audit-logs': typeof AppAdminAuditLogsRoute
  '/app/admin/export': typeof AppAdminExportRoute
  '/app/admin/feature-flags': typeof AppAdminFeatureFlagsRoute
  '/app/admin/metrics': typeof AppAdminMetricsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/analysis/$id': typeof AppAnalysisIdRoute
  '/app/projects/$id': typeof AppProjectsIdRoute
  '/app/projects/new': typeof AppProjectsNewRoute
  '/app/projects': typeof AppProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/metrics': typeof ApiMetricsRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/history': typeof AppHistoryRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/ai-usage': typeof AppAdminAiUsageRoute
  '/app/admin/api-metrics': typeof AppAdminApiMetricsRoute
  '/app/admin/audit-logs': typeof AppAdminAuditLogsRoute
  '/app/admin/export': typeof AppAdminExportRoute
  '/app/admin/feature-flags': typeof AppAdminFeatureFlagsRoute
  '/app/admin/metrics': typeof AppAdminMetricsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/analysis/$id': typeof AppAnalysisIdRoute
  '/app/projects/$id': typeof AppProjectsIdRoute
  '/app/projects/new': typeof AppProjectsNewRoute
  '/app/projects/': typeof AppProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/health'
    | '/login'
    | '/register'
    | '/api/metrics'
    | '/app/admin'
    | '/app/analytics'
    | '/app/history'
    | '/app/inbox'
    | '/app/notifications'
    | '/app/profile'
    | '/app/settings'
    | '/auth/callback'
    | '/app/'
    | '/app/admin/ai-usage'
    | '/app/admin/api-metrics'
    | '/app/admin/audit-logs'
    | '/app/admin/export'
    | '/app/admin/feature-flags'
    | '/app/admin/metrics'
    | '/app/admin/users'
    | '/app/analysis/$id'
    | '/app/projects/$id'
    | '/app/projects/new'
    | '/app/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/health'
    | '/login'
    | '/register'
    | '/api/metrics'
    | '/app/admin'
    | '/app/analytics'
    | '/app/history'
    | '/app/inbox'
    | '/app/notifications'
    | '/app/profile'
    | '/app/settings'
    | '/auth/callback'
    | '/app'
    | '/app/admin/ai-usage'
    | '/app/admin/api-metrics'
    | '/app/admin/audit-logs'
    | '/app/admin/export'
    | '/app/admin/feature-flags'
    | '/app/admin/metrics'
    | '/app/admin/users'
    | '/app/analysis/$id'
    | '/app/projects/$id'
    | '/app/projects/new'
    | '/app/projects'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/health'
    | '/login'
    | '/register'
    | '/api/metrics'
    | '/app/admin'
    | '/app/analytics'
    | '/app/history'
    | '/app/inbox'
    | '/app/notifications'
    | '/app/profile'
    | '/app/settings'
    | '/auth/callback'
    | '/app/'
    | '/app/admin/ai-usage'
    | '/app/admin/api-metrics'
    | '/app/admin/audit-logs'
    | '/app/admin/export'
    | '/app/admin/feature-flags'
    | '/app/admin/metrics'
    | '/app/admin/users'
    | '/app/analysis/$id'
    | '/app/projects/$id'
    | '/app/projects/new'
    | '/app/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HealthRoute: typeof HealthRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiMetricsRoute: typeof ApiMetricsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inbox': {
      id: '/app/inbox'
      path: '/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/metrics': {
      id: '/api/metrics'
      path: '/api/metrics'
      fullPath: '/api/metrics'
      preLoaderRoute: typeof ApiMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/projects/': {
      id: '/app/projects/'
      path: '/projects'
      fullPath: '/app/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects/new': {
      id: '/app/projects/new'
      path: '/projects/new'
      fullPath: '/app/projects/new'
      preLoaderRoute: typeof AppProjectsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects/$id': {
      id: '/app/projects/$id'
      path: '/projects/$id'
      fullPath: '/app/projects/$id'
      preLoaderRoute: typeof AppProjectsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analysis/$id': {
      id: '/app/analysis/$id'
      path: '/analysis/$id'
      fullPath: '/app/analysis/$id'
      preLoaderRoute: typeof AppAnalysisIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/metrics': {
      id: '/app/admin/metrics'
      path: '/metrics'
      fullPath: '/app/admin/metrics'
      preLoaderRoute: typeof AppAdminMetricsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/feature-flags': {
      id: '/app/admin/feature-flags'
      path: '/feature-flags'
      fullPath: '/app/admin/feature-flags'
      preLoaderRoute: typeof AppAdminFeatureFlagsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/export': {
      id: '/app/admin/export'
      path: '/export'
      fullPath: '/app/admin/export'
      preLoaderRoute: typeof AppAdminExportRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/audit-logs': {
      id: '/app/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/app/admin/audit-logs'
      preLoaderRoute: typeof AppAdminAuditLogsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/api-metrics': {
      id: '/app/admin/api-metrics'
      path: '/api-metrics'
      fullPath: '/app/admin/api-metrics'
      preLoaderRoute: typeof AppAdminApiMetricsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/ai-usage': {
      id: '/app/admin/ai-usage'
      path: '/ai-usage'
      fullPath: '/app/admin/ai-usage'
      preLoaderRoute: typeof AppAdminAiUsageRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminAiUsageRoute: typeof AppAdminAiUsageRoute
  AppAdminApiMetricsRoute: typeof AppAdminApiMetricsRoute
  AppAdminAuditLogsRoute: typeof AppAdminAuditLogsRoute
  AppAdminExportRoute: typeof AppAdminExportRoute
  AppAdminFeatureFlagsRoute: typeof AppAdminFeatureFlagsRoute
  AppAdminMetricsRoute: typeof AppAdminMetricsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAiUsageRoute: AppAdminAiUsageRoute,
  AppAdminApiMetricsRoute: AppAdminApiMetricsRoute,
  AppAdminAuditLogsRoute: AppAdminAuditLogsRoute,
  AppAdminExportRoute: AppAdminExportRoute,
  AppAdminFeatureFlagsRoute: AppAdminFeatureFlagsRoute,
  AppAdminMetricsRoute: AppAdminMetricsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppInboxRoute: typeof AppInboxRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAnalysisIdRoute: typeof AppAnalysisIdRoute
  AppProjectsIdRoute: typeof AppProjectsIdRoute
  AppProjectsNewRoute: typeof AppProjectsNewRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppInboxRoute: AppInboxRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppAnalysisIdRoute: AppAnalysisIdRoute,
  AppProjectsIdRoute: AppProjectsIdRoute,
  AppProjectsNewRoute: AppProjectsNewRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HealthRoute: HealthRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiMetricsRoute: ApiMetricsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
